version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}